os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - git clone https://github.com/libuv/libuv.git && cd libuv && sudo sh autogen.sh && sudo ./configure && sudo make && sudo make install
  - cd $TRAVIS_BUILD_DIR
script:
  - make debug
  - make
  - make test
